map ctrl+plus change_font_size all +2.0
map ctrl+equal change_font_size all +2.0
map ctrl+kp_add change_font_size all +2.0

map ctrl+minus change_font_size all -2.0
map ctrl+kp_subtract change_font_size all -2.0

font_family        caskaydiacove nerd font

font_size 10.0

window_padding_width 11 12

placement_strategy top-left

cursor            #d0d9fe
cursor_text_color #1e222a

foreground #c0caf5
background #1e222a

background_opacity 1 

selection_foreground none
#selection_background none
selection_background #3b3f48



# normal colors

# black
color0 #0b0c15
# red
color1 #d2556c
# green
color2 #7cd47b
# yellow
color3 #efb184
# blue
color4 #6ca1f3
# magenta
color5 #b78df0
# cyan
color6 #69bcf4
# white
color7 #c0caf5

# bright colors

# bright black
color8 #39404a
# bright red
color9  #f7768e
# bright green
color10 #85e89d
# bright yellow
color11 #f4cf8d
# bright blue
color12 #8fb9ff
# bright magenta
color13 #d9a3ff
# bright cyan
color14 #8fd3ff
# bright white
color15 #f0f3f6

enable_audio_bell no
confirm_os_window_close 0
close_on_child_death no
shell_integration no-cursor

